{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--29fcfc9b-dfe9-4636-a1b1-ddbb5971660d",
    "created": "2024-08-13T16:07:52.344305Z",
    "modified": "2024-08-13T16:07:52.344309Z",
    "name": "No Title Available",
    "description": "Pydio version 8.2.0 and earlier contains a Cross Site Scripting (XSS) vulnerability in ./core/vendor/meenie/javascript-packer/example-inline.php line 48; ./core/vendor/dapphp/securimage/examples/test.mysql.static.php lines: 114,118 that can result in an unauthenticated remote attacker manipulating the web client via XSS code injection. This attack appear to be exploitable via the victim openning a specially crafted URL. This vulnerability appears to have been fixed in version 8.2.1.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2018-1999016"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://www.mike-gualtieri.com/files/Pydio-8-VulnerabilityDisclosure-Jul18.txt"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://pydio.com/en/community/releases/pydio-core/pydio-821-security-release"
        }
    ]
}