{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--0643a501-d8c2-48d1-a4f0-bb96a777faf0",
    "created": "2024-08-13T16:06:30.578851Z",
    "modified": "2024-08-13T16:06:30.578855Z",
    "name": "No Title Available",
    "description": "models/metadata.py in the pikepdf package 1.3.0 through 2.9.2 for Python allows XXE when parsing XMP metadata entries.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2021-29421"
        }
    ],
    "references": [
        {
            "url": "https://github.com/pikepdf/pikepdf/commit/3f38f73218e5e782fe411ccbb3b44a793c0b343a"
        },
        {
            "name": "FEDORA-2021-4bf9909a76",
            "tags": [
                "vendor-advisory"
            ],
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3QFLBBYGEDNXJ7FS6PIWTVI4T4BUPGEQ/"
        },
        {
            "name": "FEDORA-2021-d97bc581be",
            "tags": [
                "vendor-advisory"
            ],
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/36P4HTLBJPO524WMQWW57N3QRF4RFSJG/"
        },
        {
            "url": "https://github.com/pikepdf/pikepdf/blob/v2.10.0/docs/release_notes.rst#v2100"
        }
    ]
}