{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--e00ef77b-27e0-4380-9a85-132a8ee487d0",
    "created": "2024-08-13T16:14:15.263446Z",
    "modified": "2024-08-13T16:14:15.26345Z",
    "name": "No Title Available",
    "description": "pivotx/modules/module_image.php in PivotX 2.2.2 allows remote attackers to obtain sensitive information via a non-existent file in the image parameter, which reveals the installation path in an error message.  NOTE: the provenance of this information is unknown; the details are obtained solely from third party information.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2011-0775"
        }
    ],
    "references": [
        {
            "name": "70675",
            "tags": [
                "vdb-entry",
                "x_refsource_OSVDB"
            ],
            "url": "http://osvdb.org/70675"
        },
        {
            "name": "43041",
            "tags": [
                "third-party-advisory",
                "x_refsource_SECUNIA"
            ],
            "url": "http://secunia.com/advisories/43041"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://pivot-weblog.svn.sf.net/viewvc/pivot-weblog?view=revision&revision=3463"
        },
        {
            "name": "pivotx-image-info-disc(64977)",
            "tags": [
                "vdb-entry",
                "x_refsource_XF"
            ],
            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/64977"
        }
    ]
}