{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--3ba20fb0-4aa1-4469-95e1-a6f9f54b7df6",
    "created": "2024-08-13T16:06:51.255249Z",
    "modified": "2024-08-13T16:06:51.255253Z",
    "name": "No Title Available",
    "description": "An issue has been discovered in GitLab CE/EE affecting all versions starting with 12.6. Under a special condition it was possible to access data of an internal repository through a public project fork as an anonymous user.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2021-22200"
        }
    ],
    "credits": [
        {
            "lang": "en",
            "value": "This vulnerability has been discovered internally by the GitLab team"
        }
    ],
    "metrics": [
        {
            "cvssV3_1": {
                "attackComplexity": "HIGH",
                "attackVector": "NETWORK",
                "availabilityImpact": "NONE",
                "baseScore": 5.9,
                "baseSeverity": "MEDIUM",
                "confidentialityImpact": "HIGH",
                "integrityImpact": "NONE",
                "privilegesRequired": "NONE",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "version": "3.1"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/247523"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22200.json"
        }
    ]
}