{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--fe10c122-d245-4d67-b631-5f0f65f608a0",
    "created": "2024-08-13T16:03:52.046108Z",
    "modified": "2024-08-13T16:03:52.046112Z",
    "name": "Command Injection",
    "description": "This affects the package Gerapy from 0 and before 0.9.3. The input being passed to Popen, via the project_configure endpoint, isn\u2019t being sanitized.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2020-7698"
        }
    ],
    "credits": [
        {
            "lang": "en",
            "value": "Snyk Security Team"
        }
    ],
    "metrics": [
        {
            "cvssV3_1": {
                "attackComplexity": "HIGH",
                "attackVector": "NETWORK",
                "availabilityImpact": "HIGH",
                "baseScore": 8.1,
                "baseSeverity": "HIGH",
                "confidentialityImpact": "HIGH",
                "integrityImpact": "HIGH",
                "privilegesRequired": "NONE",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "version": "3.1"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://snyk.io/vuln/SNYK-PYTHON-GERAPY-572470"
        },
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://github.com/Gerapy/Gerapy/commit/e8446605eb2424717418eae199ec7aad573da2d2"
        }
    ]
}