{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--d5381df1-db92-4752-a966-f4602b65da11",
    "created": "2024-08-13T16:15:24.381779Z",
    "modified": "2024-08-13T16:15:24.381783Z",
    "name": "No Title Available",
    "description": "IBM Maximo Asset Management 7.6.1.1 generates an error message that includes sensitive information that could be used in further attacks against the system. IBM X-Force ID: 164554.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2019-4512"
        }
    ],
    "metrics": [
        {
            "cvssV3_0": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "NONE",
                "baseScore": 4.3,
                "baseSeverity": "MEDIUM",
                "confidentialityImpact": "LOW",
                "exploitCodeMaturity": "UNPROVEN",
                "integrityImpact": "NONE",
                "privilegesRequired": "LOW",
                "remediationLevel": "OFFICIAL_FIX",
                "reportConfidence": "CONFIRMED",
                "scope": "UNCHANGED",
                "temporalScore": 3.8,
                "temporalSeverity": "LOW",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.0/AV:N/I:N/C:L/S:U/UI:N/A:N/PR:L/AC:L/RC:C/E:U/RL:O",
                "version": "3.0"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://www.ibm.com/support/pages/node/1075413"
        },
        {
            "name": "ibm-maximo-cve20194512-info-disc (164554)",
            "tags": [
                "vdb-entry",
                "x_refsource_XF"
            ],
            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/164554"
        }
    ]
}