{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--db63a63f-0d3d-4c31-be79-1e906a86bf96",
    "created": "2024-08-13T16:07:25.787897Z",
    "modified": "2024-08-13T16:07:25.787901Z",
    "name": "No Title Available",
    "description": "Cloud Foundry Loggregator, versions 89.x prior to 89.5 or 96.x prior to 96.1 or 99.x prior to 99.1 or 101.x prior to 101.9 or 102.x prior to 102.2, does not handle errors thrown while constructing certain http requests. A remote authenticated user may construct malicious requests to cause the traffic controller to leave dangling TCP connections, which could cause denial of service.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2018-1269"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://www.cloudfoundry.org/blog/cve-2018-1269"
        }
    ]
}