{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--b35d66a1-15d5-47b1-b585-118a0db45280",
    "created": "2024-08-13T16:06:42.399937Z",
    "modified": "2024-08-13T16:06:42.399941Z",
    "name": "No Title Available",
    "description": "A flaw was found in Moodle in versions 3.11 to 3.11.3, 3.10 to 3.10.7, 3.9 to 3.9.10 and earlier unsupported versions. A remote code execution risk when restoring backup files was identified.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2021-3943"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2021963"
        },
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://moodle.org/mod/forum/discuss.php?d=429095"
        }
    ]
}