{
    "type": "relationship",
    "spec_version": "2.1",
    "id": "relationship--3b61085b-1957-4ba6-888e-9da1035e0d95",
    "created": "2024-08-13T14:51:23.556825Z",
    "modified": "2024-08-13T14:51:23.556827Z",
    "relationship_type": "uses",
    "source_ref": "intrusion-set--84c205fa-8bd2-492f-b392-44521e3e0e98",
    "target_ref": "tool--35162165-2d2a-48f4-9b09-9b8c4becb26b",
    "object_marking_refs": [
        "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
    ],
    "external_references": [
        {
            "source_name": "Symantec WastedLocker June 2020",
            "url": "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/wastedlocker-ransomware-us",
            "description": "Symantec Threat Intelligence. (2020, June 25). WastedLocker: Symantec Identifies Wave of Attacks Against U.S. Organizations. Retrieved May 20, 2021."
        }
    ],
    "description": "(Citation: Symantec WastedLocker June 2020)",
    "x_mitre_version": "1.0",
    "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5"
}